JUMBO_CATEGORIES = [
    "mi-bebe",
    "quesos-y-fiambres",
    # "deportes",
    # "congelados",
    # "panaderia-y-pasteleria",
    # "libreria",
    # "desayuno-y-dulces",
    # "pescaderia",
    # "jugueteria",
    # "perfumeria",
    # "platos-preparados-y-pastas",
    # "farmacia",
    # "pollo-y-pavo",
    # "hogar",
    # "vinos-cervezas-y-licores",
    # "electro-y-tecnologia",
    # "lacteos-y-bebidas-vegetales",
    # "despensa",
    # "frutas-y-verduras",
    # "limpieza",
    # "carnes-rojas",
    # "bebidas-aguas-y-jugos",
    # "mascotas",
]

REPLACE_STRINGS = [
    ('\\"', '"'),
    ('\\"', '"'),
    ('["{', "[{"),
    ('}"]', "}]"),
    ('{\\"', '{"'),
    (',\\"', ',"'),
    ('\\",', '",'),
    ('\\"}', '"}'),
    ('\\":', '":'),
    (':\\"', ':"'),
    ('[\\"', '["'),
    ('\\"]', '"]'),
]
